name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      example-input:
        description: 'An example input'
        required: true
        default: 'default value'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
      - uses: actions/setup-java@v4
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: my-public-project
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean deploy
